name: deploy-dev

concurrency:
  group: deploy-dev

on:
  push:
    branches:
      - main
      - b-1
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://shypyard-web-dev.herokuapp.com/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: node index.js
